
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:mysql}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}


#kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.producer.key-serializer=${KAFKA_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
spring.kafka.producer.value-serializer=${KAFKA_VALUE_SERIALIZER:org.springframework.kafka.support.serializer.JsonSerializer}

spring.kafka.producer.properties.enable.idempotence=${KAFKA_ENABLE_IDEMPOTENCE:true}
spring.kafka.producer.properties.acks=${KAFKA_ACKS:all}
spring.kafka.producer.properties.retries=${KAFKA_RETRIES:5}
spring.kafka.producer.properties.max.in.flight.requests.per.connection=${KAFKA_MAX_IN_FLIGHT:5}